In [1]:
import numpy as np

In [2]:
data

NameError: name 'data' is not defined

In [3]:
#创建ndarray
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2L, 4L)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
np.empty(2)

array([  2.12199579e-314,   0.00000000e+000])

In [15]:
np.empty((2,3,2))

array([[[  5.24605701e-316,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.eye(1)

array([[ 1.]])

In [20]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
arr1=np.array([1,2,3],dtype=np.float64)

In [23]:
arr2=np.array([1,2,3],dtype=np.int32)

In [24]:
arr1

array([ 1.,  2.,  3.])

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)

In [30]:
float_arr.dtype

dtype('float64')

In [31]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [32]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [33]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25','-9.6','43'],dtype=np.float64)

In [35]:
numeric_strings

array([  1.25,  -9.6 ,  43.  ])

In [36]:
int_array=np.arange(10)

In [37]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [39]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [40]:
empty_uint32 = np.empty(8,dtype='u4')

In [41]:
empty_uint32

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248], dtype=uint32)

In [42]:
arr = np.array([[1,2,3],[4,5,6]])

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [45]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
arr !

SyntaxError: invalid syntax (<ipython-input-46-33c1247fe05c>, line 1)

In [47]:
arr **3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [48]:
1/arr

array([[1, 0, 0],
       [0, 0, 0]])

In [49]:
arr = np.array(10)

In [50]:
arr

array(10)

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] - 12

array([-7, -6, -5])

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5:8] = 12

In [58]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice = arr[5:8]

In [60]:
arr_slice

array([12, 12, 12])

In [61]:
arr_slice[1]

12

In [62]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [63]:
arr_slice[:]

array([12, 12, 12])

In [64]:
arr_slice[1:]

array([12, 12])

In [65]:
arr_slice[1:2]

array([12])

In [66]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0,2]

3

In [70]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [72]:
arr3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
arr3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [76]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
old_values = arr3d[0].copy()

In [79]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr3d[0] = 42

In [81]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[0] = old_values

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[1,0]

array([7, 8, 9])

In [85]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [86]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr2d[:2,:1]

array([[1],
       [4]])

In [90]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [91]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr2d[1,:2]

array([4, 5])

In [93]:
arr2d[2,:1]

array([7])

In [94]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [95]:
#布尔值索引

In [96]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [97]:
data=randn(7,4)

NameError: name 'randn' is not defined

In [98]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [99]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [100]:
import numpy as np

In [101]:
data = randn(7,4)

NameError: name 'randn' is not defined

In [102]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [103]:
arr = np.empty((8,4))

In [104]:
for i in range(8):
    arr[i] = i

In [105]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [106]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [107]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [108]:
arr = np.arange(32).reshape((8,4))

In [109]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [110]:
arr = np.arange(15).reshape((3,5))

In [111]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [113]:
arr = np.random.randn(6,3)

In [114]:
np.dot(arr.T, arr)

array([[ 7.24067764,  1.9606646 ,  1.15768486],
       [ 1.9606646 ,  2.27917898,  1.87856345],
       [ 1.15768486,  1.87856345,  8.55205745]])

In [115]:
arr = np.arange(16).reshape((2,2,4))

In [116]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [117]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [118]:
arr.transpose((0,0,3))

ValueError: repeated axis in transpose

In [119]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [120]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [121]:
arr = np.arange(10)

In [122]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [123]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [124]:
x = randn(8)

NameError: name 'randn' is not defined

In [125]:
x = np.randn(8)

AttributeError: 'module' object has no attribute 'randn'

In [126]:
x = np.array([1,6,8,9])

In [127]:
y = np.array([6,3,12,78])

In [128]:
np.maximum(x,y)

array([ 6,  6, 12, 78])

In [129]:
z = -5

In [130]:
np.abs(z)

5

In [131]:
np.sqrt(z)

D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


nan

In [132]:
np.square(z)

25

In [133]:
points = np.arange(-5,5,0.01)

In [134]:
xs,ys = np.meshgrid(points,points)

In [135]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [136]:
import matplotlib.pyplot as plt

In [137]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [138]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [141]:
plt.imshow(z,cmap=plt.cm.gray); plt.colorbar()

In [142]:
arr = np.random.randn(5,4)

In [143]:
arr

array([[ 1.3464635 , -0.06853389, -0.17845779, -0.82426364],
       [-0.76716325,  0.09274474, -0.10984925, -0.52254598],
       [-0.05205924, -0.0791049 , -0.37021677, -0.54444975],
       [ 1.42083017,  0.7427499 , -1.20648304,  0.90161247],
       [ 0.41023074,  1.56498644,  0.5169621 ,  0.30716408]])

In [144]:
arr.mean()

0.12903083101275106

In [145]:
np.mean(arr)

0.12903083101275106

In [146]:
arr.sum()

2.5806166202550211

In [1]:
arr

NameError: name 'arr' is not defined

In [2]:
#用于布尔型数组的方法

In [3]:
arr = randn(100)

NameError: name 'randn' is not defined

In [4]:
arr = np.random.randn(100)

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
arr = np.random.randn(100)

In [7]:
arr

array([-0.46956667, -2.4140303 , -0.58154339,  0.65172504, -0.40360421,
        0.49186896, -0.19517201,  0.82680253, -0.17615004,  0.23711612,
       -1.0647973 ,  1.24542773, -0.90425016,  0.3531434 ,  0.50278598,
        0.47361293, -0.04737082,  0.26236793, -0.26045057,  0.65785706,
        2.22693787, -0.82051602,  1.95542549,  0.76150421, -1.55930286,
       -1.49367331,  0.5941243 , -0.49033774,  0.37027188,  0.99053992,
        0.56018519,  0.33005511,  0.39778155, -0.32988729,  1.36361365,
        0.12290416, -0.2672123 , -0.70202316, -0.00866858,  0.98525605,
        0.84346031,  0.67319378,  0.60556849, -0.68962803, -0.27646293,
       -1.55432805,  1.33671533,  0.96532821,  0.20192839,  0.7632211 ,
        0.51570874, -0.05834322,  0.23509625,  1.09782428, -1.8280053 ,
        1.12945597, -0.56092413, -0.31748863,  0.44937692, -1.25689083,
        0.00849035,  1.14928434, -0.23782383,  0.28559692,  0.32631645,
        1.19066049, -0.20571707,  1.38373935, -0.41534995, -1.02

In [8]:
(arr>0).sum()

60

In [9]:
bools=np.array([False,False,True,True])

In [10]:
bool

bool

In [11]:
bools.any()

True

In [12]:
bools.all()

False

In [13]:
arr=np.random.randn(8)

In [14]:
arr

array([-0.39541683, -0.79117836, -0.12716103, -0.69913169, -0.57399647,
        1.61663702,  0.80102185, -0.578199  ])

In [15]:
arr.sort()

In [16]:
arr

array([-0.79117836, -0.69913169, -0.578199  , -0.57399647, -0.39541683,
       -0.12716103,  0.80102185,  1.61663702])

In [17]:
arr=np.random=randn(5,3)

NameError: name 'randn' is not defined

In [18]:
arr=np.random.randn(5,3)

In [19]:
arr

array([[-0.67506978, -0.0965836 , -0.0263634 ],
       [-0.12000721, -0.33515826,  1.38901065],
       [-0.70550281, -1.57251448,  0.22037327],
       [ 0.03649762, -1.40661405, -1.45776773],
       [-0.09232843, -1.10850276,  0.80487996]])

In [20]:
arr.sort(1)

In [21]:
arr

array([[-0.67506978, -0.0965836 , -0.0263634 ],
       [-0.33515826, -0.12000721,  1.38901065],
       [-1.57251448, -0.70550281,  0.22037327],
       [-1.45776773, -1.40661405,  0.03649762],
       [-1.10850276, -0.09232843,  0.80487996]])

In [22]:
large_arr=np.random.randn(100)

In [23]:
large_arr.sort()

In [24]:
large_arr[int(0.05*len(large_arr))]

-1.5879550345294946

In [25]:
#唯一化及其他的集合逻辑

In [26]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [27]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [28]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [29]:
ints=np.array([3,3,3,2,2,1,1,4,4])

In [30]:
np.unique(ints)

array([1, 2, 3, 4])

In [31]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [32]:
values=np.array([6,0,0,3,2,5,6])

In [33]:
np.inld(values,[2,3,6])

AttributeError: 'module' object has no attribute 'inld'

In [34]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [35]:
#用于数组的文件输入输入输出
#将数组以二进制格式保存到磁盘

In [36]:
arr=np.arange(10)

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.save("some_array",arr)

In [39]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.savez('array_archive.npz',a=arr,b=arr)

In [42]:
arch=np.load('array_archive.npz')

In [44]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#存取文本文件
!cat array_ex.txt

'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [47]:
arr=np.loadtxt('./array_ex.txt',deliniter=',')

TypeError: loadtxt() got an unexpected keyword argument 'deliniter'

In [48]:
#线性代数

In [49]:
x = np.array([[1,2,3],[4,5,6]])

In [50]:
y=np.array([[6,23],[-1,7],[8,9]])

In [51]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [53]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [54]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [55]:
from numpy.linalg import inv,qr

In [57]:
x=np.random.randn(5,5)

In [58]:
mat = x.T.dot(x)

In [59]:
inv(mat)

array([[ 0.45856815,  0.28216852, -0.0230576 ,  0.17461232, -0.19243591],
       [ 0.28216852,  0.80801096,  0.24385861,  0.0052008 , -0.46296719],
       [-0.0230576 ,  0.24385861,  1.82859499, -0.89172089,  0.3629743 ],
       [ 0.17461232,  0.0052008 , -0.89172089,  0.67559232, -0.23784272],
       [-0.19243591, -0.46296719,  0.3629743 , -0.23784272,  0.64508673]])

In [60]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   0.00000000e+00,  -1.38777878e-17,
          5.55111512e-17,   0.00000000e+00],
       [  2.22044605e-16,   1.00000000e+00,  -2.22044605e-16,
          0.00000000e+00,   2.22044605e-16],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
         -5.55111512e-17,   1.11022302e-16],
       [  2.22044605e-16,   5.55111512e-17,  -3.60822483e-16,
          1.00000000e+00,  -1.66533454e-16],
       [ -1.11022302e-16,  -4.44089210e-16,   4.44089210e-16,
         -2.22044605e-16,   1.00000000e+00]])

In [61]:
q,r=qr(mat)

In [62]:
q

array([[-0.84373627,  0.02543788, -0.49348902, -0.02570295, -0.20801432],
       [ 0.21169313, -0.70824731, -0.20831672,  0.39966186, -0.50044612],
       [ 0.19009527,  0.30980151, -0.50953573,  0.67402895,  0.39235843],
       [ 0.45342542,  0.19552344, -0.62849624, -0.54320309, -0.25709698],
       [-0.0395512 , -0.60293638, -0.24174067, -0.300375  ,  0.69730892]])

In [63]:
r

array([[-4.08537028,  0.88103223,  2.1871835 ,  4.53443576, -0.20655055],
       [ 0.        , -4.77579057,  3.09637752,  2.60176156, -5.14514706],
       [ 0.        ,  0.        , -2.00618689, -3.80694022, -0.64952412],
       [ 0.        ,  0.        ,  0.        , -1.11235074, -0.87575746],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.08095375]])

In [64]:
#随机数生成
samples = np.random.normal(size=(4,4))

In [65]:
samples

array([[-1.1231914 ,  1.63124093,  0.30043599,  0.00880393],
       [-0.80790034, -0.03280786, -1.37832562, -0.28655609],
       [-1.28689574,  1.3404852 , -0.26338501, -1.65600585],
       [-1.23543048,  0.07415372, -0.28518432, -0.81608941]])

In [66]:
from random import normalvariate

In [67]:
N=1000000

In [69]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 71.9 ms per loop


In [70]:
#随机漫步

In [71]:
import random

In [72]:
position = 0

In [73]:
walk=[position]

In [74]:
steps=1000

In [75]:
for i in xrange(steps):
    step=1 if random.randint(0,1) else -1
    position+=step
    walk.append(position)

In [76]:
nsteps=1000

In [77]:
draws=np.random.randint(0,2,size=nsteps)

In [78]:
steps=np.where(draws > 0,1,-1)

In [79]:
walk=steps.cumsum()

In [80]:
walk.min()

-36

In [81]:
walk.max()

5

In [82]:
(np.abs(walk)>=10).argmax()

117

In [83]:
#一次模拟多个随机漫步
nwalks=5000
nsteps=1000
draws=np.random.randint(0,2,size=(nwalks,nsteps))
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)

In [84]:
walks

array([[ -1,   0,  -1, ..., -44, -45, -44],
       [  1,   0,  -1, ...,  -2,  -3,  -4],
       [ -1,   0,   1, ...,   4,   3,   2],
       ..., 
       [ -1,  -2,  -1, ...,  18,  19,  18],
       [ -1,   0,  -1, ...,  32,  33,  34],
       [  1,   0,   1, ..., -30, -29, -30]])

In [85]:
walks.max()

106

In [86]:
walks.min()

-117

In [87]:
hits30=(np.abs(walks)>=30).any(1)

In [88]:
hits30

array([ True, False,  True, ..., False,  True,  True], dtype=bool)

In [89]:
hits30.sum()

3408

In [90]:
crossing_times=(np.abs(walks[hits30])>30).argmax(1)

In [91]:
crossing_times.mean()

487.87969483568077

In [92]:
steps=np.random.normal(loc=0,scale=0.25,size=(nwalks,nsteps))

In [93]:
steps

array([[ 0.31322356, -0.38508654, -0.04859788, ...,  0.02411625,
         0.07296747, -0.14957016],
       [-0.30021851,  0.10343881, -0.31165668, ...,  0.38614259,
         0.26874355,  0.08328946],
       [ 0.23164146,  0.2051346 , -0.00185877, ..., -0.06398622,
        -0.2609183 ,  0.16993086],
       ..., 
       [ 0.05513144, -0.01752467, -0.14909826, ..., -0.22347419,
         0.15877407, -0.04896235],
       [-0.26237556,  0.54745599, -0.18125165, ..., -0.0417021 ,
        -0.56325565, -0.32604228],
       [ 0.54134738,  0.21529381,  0.36148017, ..., -0.207141  ,
        -0.07740566,  0.03877498]])