In [1]:
import numpy as np

In [2]:
data

NameError: name 'data' is not defined

In [3]:
#创建ndarray
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2L, 4L)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
np.empty(2)

array([  2.12199579e-314,   0.00000000e+000])

In [15]:
np.empty((2,3,2))

array([[[  5.24605701e-316,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.eye(1)

array([[ 1.]])

In [20]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
arr1=np.array([1,2,3],dtype=np.float64)

In [23]:
arr2=np.array([1,2,3],dtype=np.int32)

In [24]:
arr1

array([ 1.,  2.,  3.])

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)

In [30]:
float_arr.dtype

dtype('float64')

In [31]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [32]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [33]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25','-9.6','43'],dtype=np.float64)

In [35]:
numeric_strings

array([  1.25,  -9.6 ,  43.  ])

In [36]:
int_array=np.arange(10)

In [37]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [39]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [40]:
empty_uint32 = np.empty(8,dtype='u4')

In [41]:
empty_uint32

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248], dtype=uint32)

In [42]:
arr = np.array([[1,2,3],[4,5,6]])

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [45]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
arr !

SyntaxError: invalid syntax (<ipython-input-46-33c1247fe05c>, line 1)

In [47]:
arr **3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [48]:
1/arr

array([[1, 0, 0],
       [0, 0, 0]])

In [49]:
arr = np.array(10)

In [50]:
arr

array(10)

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] - 12

array([-7, -6, -5])

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5:8] = 12

In [58]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice = arr[5:8]

In [60]:
arr_slice

array([12, 12, 12])

In [61]:
arr_slice[1]

12

In [62]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [63]:
arr_slice[:]

array([12, 12, 12])

In [64]:
arr_slice[1:]

array([12, 12])

In [65]:
arr_slice[1:2]

array([12])

In [66]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0,2]

3

In [70]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [72]:
arr3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
arr3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [76]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
old_values = arr3d[0].copy()

In [79]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr3d[0] = 42

In [81]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[0] = old_values

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[1,0]

array([7, 8, 9])

In [85]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [86]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr2d[:2,:1]

array([[1],
       [4]])

In [90]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [91]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr2d[1,:2]

array([4, 5])

In [93]:
arr2d[2,:1]

array([7])

In [94]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [95]:
#布尔值索引

In [96]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [97]:
data=randn(7,4)

NameError: name 'randn' is not defined

In [98]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [99]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [100]:
import numpy as np

In [101]:
data = randn(7,4)

NameError: name 'randn' is not defined

In [102]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [103]:
arr = np.empty((8,4))

In [104]:
for i in range(8):
    arr[i] = i

In [105]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [106]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [107]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [108]:
arr = np.arange(32).reshape((8,4))

In [109]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [110]:
arr = np.arange(15).reshape((3,5))

In [111]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [113]:
arr = np.random.randn(6,3)

In [114]:
np.dot(arr.T, arr)

array([[ 7.24067764,  1.9606646 ,  1.15768486],
       [ 1.9606646 ,  2.27917898,  1.87856345],
       [ 1.15768486,  1.87856345,  8.55205745]])

In [115]:
arr = np.arange(16).reshape((2,2,4))

In [116]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [117]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [118]:
arr.transpose((0,0,3))

ValueError: repeated axis in transpose

In [119]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [120]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [121]:
arr = np.arange(10)

In [122]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [123]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [124]:
x = randn(8)

NameError: name 'randn' is not defined

In [125]:
x = np.randn(8)

AttributeError: 'module' object has no attribute 'randn'

In [126]:
x = np.array([1,6,8,9])

In [127]:
y = np.array([6,3,12,78])

In [128]:
np.maximum(x,y)

array([ 6,  6, 12, 78])

In [129]:
z = -5

In [130]:
np.abs(z)

5

In [131]:
np.sqrt(z)

D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


nan

In [132]:
np.square(z)

25

In [133]:
points = np.arange(-5,5,0.01)

In [134]:
xs,ys = np.meshgrid(points,points)

In [135]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [136]:
import matplotlib.pyplot as plt

In [137]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [138]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [141]:
plt.imshow(z,cmap=plt.cm.gray); plt.colorbar()

In [142]:
arr = np.random.randn(5,4)

In [143]:
arr

array([[ 1.3464635 , -0.06853389, -0.17845779, -0.82426364],
       [-0.76716325,  0.09274474, -0.10984925, -0.52254598],
       [-0.05205924, -0.0791049 , -0.37021677, -0.54444975],
       [ 1.42083017,  0.7427499 , -1.20648304,  0.90161247],
       [ 0.41023074,  1.56498644,  0.5169621 ,  0.30716408]])

In [144]:
arr.mean()

0.12903083101275106

In [145]:
np.mean(arr)

0.12903083101275106

In [146]:
arr.sum()

2.5806166202550211